"""add_booking_end_column

Revision ID: 2aed8ec73ed3
Revises: 0daf4b5ad50c
Create Date: 2026-05-16 17:29:25.926464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2aed8ec73ed3'
down_revision: Union[str, Sequence[str], None] = '0daf4b5ad50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_end', sa.Time(), nullable=True))
    op.alter_column('bookings', 'client_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bookings', 'booking_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('bookings', 'booking_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'booking_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('bookings', 'booking_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('bookings', 'client_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('bookings', 'booking_end')
    # ### end Alembic commands ###
