"""add booking_services table

Revision ID: 61ccd16adea9
Revises: 99055cdcb110
Create Date: 2026-09-28 17:04:53.764248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ccd16adea9'
down_revision: Union[str, Sequence[str], None] = '99055cdcb110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_service_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('bookings_service_id_fkey'), 'bookings', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###
