"""remove client_surname from bookings

Revision ID: 99055cdcb110
Revises: 2513ba7ff9d0
Create Date: 2026-06-07 20:52:52.007594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99055cdcb110'
down_revision: Union[str, Sequence[str], None] = '2513ba7ff9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'client_surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('client_surname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
